{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"snowball_output\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "snowball_output": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "snowball output": {
                      "State": "Generated"
                    }
                  },
                  {
                    "snowball_output": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "output": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "snowball production": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "snowball productivity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "production": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "productivity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "snowball yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "snowball harvest": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "snowball crop": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "harvest": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "crop": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.NRR_percentage": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "NRR Percentage"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "NRR percentage": {
                      "State": "Generated"
                    }
                  },
                  {
                    "nrr ratio": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "nrr measurement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "nrr calculation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "nrr fraction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "nrr proportion": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "nrr part": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "nrr section": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "nrr entitlement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "nrr take": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "nrr profit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  }
                ]
              },
              "snowball_output.bop_arr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "bop_arr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "bop arr": {
                      "State": "Generated"
                    }
                  },
                  {
                    "bop_arr": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "snowball_output.cross_sell": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "cross_sell"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "cross sell": {
                      "State": "Generated"
                    }
                  },
                  {
                    "cross_sell": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "sell": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "symbol sell": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "mark sell": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "sign sell": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  }
                ]
              },
              "snowball_output.customer_churn": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "customer_churn"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer churn": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer_churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "client churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "shopper churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "snowball_output.customer_churn_rate": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "Customer Churn Rate"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer churn rate": {
                      "State": "Generated"
                    }
                  },
                  {
                    "rate": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "churn rate": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "client churn rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "consumer churn rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "user churn rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "buyer churn rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "patron churn rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "purchaser churn rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "shopper churn rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "customer churn degree": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "customer churn frequency": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "customer churn percentage": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "Customer Churn Rate Percentage": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "snowball_output.customer_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "customer_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "client key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "shopper key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.downsell": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "downsell"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "downsell": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "snowball_output.eop_arr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "eop_arr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "eop arr": {
                      "State": "Generated"
                    }
                  },
                  {
                    "eop_arr": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "snowball_output.grr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "grr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "grr": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "snowball_output.month_roll": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month_roll": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "roll": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "mth roll": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "month reel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "month cylinder": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "month spool": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "month tube": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "reel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "cylinder": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "spool": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "tube": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.month_roll.variation.date_hierarchy": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "Hierarchy": "Date Hierarchy",
                    "VariationSet": "Variation",
                    "VariationSource": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll date hierarchy": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "roll date hierarchy": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "snowball_output.month_roll.variation.date_hierarchy.day": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Day",
                    "VariationSet": "Variation",
                    "VariationSource": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "day": {
                      "State": "Generated"
                    }
                  },
                  {
                    "roll day": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "mth roll day": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  }
                ]
              },
              "snowball_output.month_roll.variation.date_hierarchy.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Month",
                    "VariationSet": "Variation",
                    "VariationSource": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "roll month": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "month roll mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "roll mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "mth roll month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  }
                ]
              },
              "snowball_output.month_roll.variation.date_hierarchy.quarter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Quarter",
                    "VariationSet": "Variation",
                    "VariationSource": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "roll quarter": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "month roll qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.846
                    }
                  },
                  {
                    "roll qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.833
                    }
                  },
                  {
                    "qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  },
                  {
                    "mth roll quarter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  }
                ]
              },
              "snowball_output.month_roll.variation.date_hierarchy.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "Hierarchy": "Date Hierarchy",
                    "HierarchyLevel": "Year",
                    "VariationSet": "Variation",
                    "VariationSource": "month_roll"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month roll year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "roll year": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "month roll yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "roll yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "mth roll year": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  }
                ]
              },
              "snowball_output.new_customer": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "new_customer"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "new customer": {
                      "State": "Generated"
                    }
                  },
                  {
                    "new_customer": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "customer": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "new client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new buyer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new purchaser": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new shopper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "snowball_output.nrr": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "nrr"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "nrr": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "snowball_output.period_type": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "period_type"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "period type": {
                      "State": "Generated"
                    }
                  },
                  {
                    "period_type": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "type": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "period category": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "period genre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "period manner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "period variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "category": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "genre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "manner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "period brand": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "period class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "snowball_output.product_churn": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "product_churn"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "product churn": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product_churn": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "churn": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "artifact churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "item churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "merchandise churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "produce churn": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "snowball_output.product_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "product_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "product key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "artifact key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "item key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "merchandise key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "produce key": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "central": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "major": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "keynote": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "snowball_output.snowball_key": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "snowball_key"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "snowball key": {
                      "State": "Generated"
                    }
                  },
                  {
                    "snowball_key": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "key": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "main": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "basic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fundamental": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "central": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "major": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "keynote": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "essential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "snowball solution": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "snowball explanation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "snowball basis": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  }
                ]
              },
              "snowball_output.upsell": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "snowball_output",
                    "ConceptualProperty": "upsell"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "upsell": {
                      "State": "Generated"
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "snowball_output_has_NRR_percentage": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.NRR_percentage"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_NRR_percentage",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.NRR_percentage": {
                    "Target": {
                      "Entity": "snowball_output.NRR_percentage"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_bop_arr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.bop_arr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_bop_arrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.bop_arr": {
                    "Target": {
                      "Entity": "snowball_output.bop_arr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_cross_sell": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.cross_sell"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_cross_sell",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.cross_sell": {
                    "Target": {
                      "Entity": "snowball_output.cross_sell"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_customer_churn": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.customer_churn"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_customer_churns",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.customer_churn": {
                    "Target": {
                      "Entity": "snowball_output.customer_churn"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_customer_churn_rate": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.customer_churn_rate"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_customer_churn_rate",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.customer_churn_rate": {
                    "Target": {
                      "Entity": "snowball_output.customer_churn_rate"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_customer_key": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.customer_key"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_customer_keys",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.customer_key": {
                    "Target": {
                      "Entity": "snowball_output.customer_key"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_downsell": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.downsell"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_downsells",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.downsell": {
                    "Target": {
                      "Entity": "snowball_output.downsell"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_eop_arr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.eop_arr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_eop_arrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.eop_arr": {
                    "Target": {
                      "Entity": "snowball_output.eop_arr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_grr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.grr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_grrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.grr": {
                    "Target": {
                      "Entity": "snowball_output.grr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_month_roll": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_month_rolls",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.month_roll": {
                    "Target": {
                      "Entity": "snowball_output.month_roll"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_new_customer": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.new_customer"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_new_customers",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.new_customer": {
                    "Target": {
                      "Entity": "snowball_output.new_customer"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_nrr": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.nrr"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_nrrs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.nrr": {
                    "Target": {
                      "Entity": "snowball_output.nrr"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_period_type": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.period_type"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_period_types",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.period_type": {
                    "Target": {
                      "Entity": "snowball_output.period_type"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_product_churn": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.product_churn"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_product_churns",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.product_churn": {
                    "Target": {
                      "Entity": "snowball_output.product_churn"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_product_key": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.product_key"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_product_keys",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.product_key": {
                    "Target": {
                      "Entity": "snowball_output.product_key"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_snowball_key": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.snowball_key"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_snowball_keys",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.snowball_key": {
                    "Target": {
                      "Entity": "snowball_output.snowball_key"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_has_upsell": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.upsell"
                      },
                      "Subject": {
                        "Role": "snowball_output"
                      }
                    },
                    "ID": "snowball_outputs_have_upsell",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output": {
                    "Target": {
                      "Entity": "snowball_output"
                    }
                  },
                  "snowball_output.upsell": {
                    "Target": {
                      "Entity": "snowball_output.upsell"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_month_roll_has_variation_date_hierarchy": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy"
                      },
                      "Subject": {
                        "Role": "snowball_output.month_roll"
                      }
                    },
                    "ID": "month_rolls_have_month_roll_date_hierarchies",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output.month_roll": {
                    "Target": {
                      "Entity": "snowball_output.month_roll"
                    }
                  },
                  "snowball_output.month_roll.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_month_roll_variation_date_hierarchy_has_day": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy.day"
                      },
                      "Subject": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy"
                      }
                    },
                    "ID": "month_roll_date_hierarchies_have_month_roll_days",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output.month_roll.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy"
                    }
                  },
                  "snowball_output.month_roll.variation.date_hierarchy.day": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy.day"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_month_roll_variation_date_hierarchy_has_month": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy.month"
                      },
                      "Subject": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy"
                      }
                    },
                    "ID": "month_roll_date_hierarchies_have_month_roll_months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output.month_roll.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy"
                    }
                  },
                  "snowball_output.month_roll.variation.date_hierarchy.month": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy.month"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_month_roll_variation_date_hierarchy_has_quarter": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy.quarter"
                      },
                      "Subject": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy"
                      }
                    },
                    "ID": "month_roll_date_hierarchies_have_month_roll_quarters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output.month_roll.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy"
                    }
                  },
                  "snowball_output.month_roll.variation.date_hierarchy.quarter": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy.quarter"
                    }
                  }
                },
                "State": "Generated"
              },
              "snowball_output_month_roll_variation_date_hierarchy_has_year": {
                "Binding": {
                  "ConceptualEntity": "snowball_output"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy.year"
                      },
                      "Subject": {
                        "Role": "snowball_output.month_roll.variation.date_hierarchy"
                      }
                    },
                    "ID": "month_roll_date_hierarchies_have_month_roll_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "snowball_output.month_roll.variation.date_hierarchy": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy"
                    }
                  },
                  "snowball_output.month_roll.variation.date_hierarchy.year": {
                    "Target": {
                      "Entity": "snowball_output.month_roll.variation.date_hierarchy.year"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "3672df76-e95f-4fd2-9cbd-b1ff44038b6e",
        "fromColumn": "Date",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a3a1a0dd-88a5-4984-a4e2-03ea5e260406"
      },
      {
        "name": "f81890a1-dcda-419e-b9a2-19d0ba7ea34e",
        "fromColumn": "EOW - Saturday",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a1804b1c-1bd9-49ab-a9d3-60896ebf5886"
      },
      {
        "name": "e31684b8-fb38-bc1b-6391-168fc851c2b5",
        "fromColumn": "month_roll",
        "fromTable": "snowball_output",
        "toColumn": "Date",
        "toTable": "Calendar"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "snowball_output",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "snowball_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d95a325-b638-4701-b86f-67e037dc1af5",
            "sourceColumn": "snowball_key",
            "summarizeBy": "none"
          },
          {
            "name": "customer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66af7053-1bd6-404b-8820-f874048704ac",
            "sourceColumn": "customer_key",
            "summarizeBy": "none"
          },
          {
            "name": "product_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6eb57f0b-75b7-446f-a899-b92a26b30ab5",
            "sourceColumn": "product_key",
            "summarizeBy": "none"
          },
          {
            "name": "month_roll",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3806ba53-f5a7-4eff-8231-cb3a5a63c89f",
            "sourceColumn": "month_roll",
            "summarizeBy": "none"
          },
          {
            "name": "period_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc73023d-9972-4537-95ab-e858493e2896",
            "sourceColumn": "period_type",
            "summarizeBy": "none"
          },
          {
            "name": "bop_arr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "67d6ee66-5964-4e87-9022-21f6e8a2a516",
            "sourceColumn": "bop_arr",
            "summarizeBy": "sum"
          },
          {
            "name": "customer_churn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "977982c9-6fc6-4610-99b3-362ef97e65ed",
            "sourceColumn": "customer_churn",
            "summarizeBy": "sum"
          },
          {
            "name": "product_churn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "11f72a15-0a3a-4a56-a0fe-61445bf65279",
            "sourceColumn": "product_churn",
            "summarizeBy": "sum"
          },
          {
            "name": "downsell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1871681e-239a-4b1b-acb2-649127254e2e",
            "sourceColumn": "downsell",
            "summarizeBy": "sum"
          },
          {
            "name": "grr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a9dbcaa9-5b32-4560-a0a6-e04978285f4e",
            "sourceColumn": "grr",
            "summarizeBy": "sum"
          },
          {
            "name": "upsell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f14a3945-3c3a-47a4-8fc3-d4617272659c",
            "sourceColumn": "upsell",
            "summarizeBy": "sum"
          },
          {
            "name": "cross_sell",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1f2fa93a-338b-4fd6-b4d8-4807ac68f464",
            "sourceColumn": "cross_sell",
            "summarizeBy": "sum"
          },
          {
            "name": "nrr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5612f1e6-43eb-49d0-85b5-0fc2cadd47ce",
            "sourceColumn": "nrr",
            "summarizeBy": "sum"
          },
          {
            "name": "new_customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "68b5d926-5191-425b-9b80-255175acc8bc",
            "sourceColumn": "new_customer",
            "summarizeBy": "sum"
          },
          {
            "name": "eop_arr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ad4121ee-1bfd-435f-9a64-408b76d13bf5",
            "sourceColumn": "eop_arr",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "db912d60-b2c9-41df-ac9a-a46f87ec557c",
        "measures": [
          {
            "name": "Customer Churn Rate",
            "expression": [
              "",
              "-1*(DIVIDE(SUM(snowball_output[customer_churn]), SUM(snowball_output[bop_arr]), 0))",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "05b06e82-407e-4e22-b7e8-0e5a19658581"
          },
          {
            "name": "NRR Percentage",
            "expression": "DIVIDE(SUM(snowball_output[nrr]), SUM(snowball_output[bop_arr]), 0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "77a627f5-0115-4600-8388-aa10aecf4992"
          }
        ],
        "partitions": [
          {
            "name": "snowball_output",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\LalithKishoreP\\Downloads\\snowball_output.csv\"),[Delimiter=\",\", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"snowball_key\", type text}, {\"customer_key\", type text}, {\"product_key\", type text}, {\"month_roll\", type date}, {\"period_type\", type text}, {\"bop_arr\", type number}, {\"customer_churn\", type number}, {\"product_churn\", type number}, {\"downsell\", type number}, {\"grr\", type number}, {\"upsell\", type number}, {\"cross_sell\", Int64.Type}, {\"nrr\", type number}, {\"new_customer\", type number}, {\"eop_arr\", type number}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([month_roll] <> #date(2018, 1, 1) and [month_roll] <> #date(2018, 2, 1) and [month_roll] <> #date(2018, 3, 1) and [month_roll] <> #date(2018, 4, 1) and [month_roll] <> #date(2018, 5, 1) and [month_roll] <> #date(2018, 6, 1) and [month_roll] <> #date(2018, 7, 1) and [month_roll] <> #date(2018, 8, 1) and [month_roll] <> #date(2018, 9, 1) and [month_roll] <> #date(2018, 10, 1) and [month_roll] <> #date(2018, 11, 1) and [month_roll] <> #date(2018, 12, 1)))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_f278d7f4-a904-4b76-bf4e-ec2018e9cd20",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "258506cc-1aa6-4246-8472-fa12bf186b4d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4cbe7bac-6381-4b90-acbe-cc9c13587363",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "827ed610-2595-4443-b4f4-916ba6d21217",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6047b37c-1cb7-4db1-b9f4-7253a455f6a5",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9d62e33b-ea59-4954-bc0f-1e3a0ee1312a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "44be6a6c-abb9-4c75-969f-09d93f84da0e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "152185b0-f907-4d47-9854-0a46f0f60c7f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9f5230d7-f098-4ade-8dc3-a95a9ac56745",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "91b1fa10-d3a3-43f5-8f7d-f6b1a396ccc1",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "66a005b8-e9c2-4d77-a0cd-13d2a0370505",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "5d97580f-57f6-41b1-82c4-01e0ba9c0bdb",
                "ordinal": 3
              }
            ],
            "lineageTag": "854f578f-9830-43cc-8a8a-5bca381d8855"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "fe6304cd-6ceb-4ae4-b6d3-91059dd64a83",
        "partitions": [
          {
            "name": "DateTableTemplate_f278d7f4-a904-4b76-bf4e-ec2018e9cd20",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ac551408e8fb4b0dae35f91f083f8b70"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5ac9313a-0917-4e5f-ae97-794a383e80a9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a3a1a0dd-88a5-4984-a4e2-03ea5e260406"
                },
                "isDefault": true,
                "relationship": "3672df76-e95f-4fd2-9cbd-b1ff44038b6e"
              }
            ]
          },
          {
            "name": "DateAsInteger",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e3db1568-2bec-43a8-a63a-adf7d428405b",
            "sourceColumn": "[DateAsInteger]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b193e7d3-0839-41a0-9469-f665d68ddfdf",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year less 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "be58495b-4fff-4040-93df-df96a117ec1a",
            "sourceColumn": "[Year less 1]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7c58a5c4-d479-4a3f-9702-f141f63b8a9e",
            "sourceColumn": "[MonthYear]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "QuarterYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "96acdbc9-92e0-403a-842e-b354c3076999",
            "sourceColumn": "[QuarterYear]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bc0cb668-2c49-4a00-9419-3cdc49235a15",
            "sourceColumn": "[MonthNo]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MonthText",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "db6838b9-b8ed-4330-90c8-815227c606d2",
            "sourceColumn": "[MonthText]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YearMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f77d8645-a660-4649-826a-894641fb7fd8",
            "sourceColumn": "[YearMonth]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YMInt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "13b3ae72-8caa-4540-86c2-3f124e39cca2",
            "sourceColumn": "[YMInt]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WeekdayNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6323a3f5-bb90-4265-8b6f-50142c4dd207",
            "sourceColumn": "[WeekdayNo]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year & Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e8d75cef-1595-413c-890f-96eb4e180f58",
            "sourceColumn": "[Year & Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b8a4fc37-8141-4e6a-a6ba-da8d3b37ddf7",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "WeekNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6870220e-057d-466b-9c1b-35c364165fcf",
            "sourceColumn": "[WeekNo]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "EOW - Saturday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2450d785-2355-46d6-a63d-5da289932596",
            "sourceColumn": "[EOW - Saturday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a1804b1c-1bd9-49ab-a9d3-60896ebf5886"
                },
                "isDefault": true,
                "relationship": "f81890a1-dcda-419e-b9a2-19d0ba7ea34e"
              }
            ]
          },
          {
            "name": "Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c4646194-5743-4a40-bff4-716aa91c64ed",
            "sourceColumn": "[Weekday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DayNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "efae8bb0-bcf2-4fb8-a587-76664e80bb93",
            "sourceColumn": "[DayNo]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DayMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "cf2360bf-7b0e-452b-a587-42a0633d7e5c",
            "sourceColumn": "[DayMonth]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6111fdb6-4220-44b6-aae7-842293fa2db6",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": [
                "ADDCOLUMNS(CALENDAR(date(2017,01,01),date(2026,12,31)),",
                "\"DateAsInteger\", FORMAT ( [Date], \"YYYYMMDD\" ), ",
                "\"Year\", FORMAT([Date], \"yyyy\"), ",
                "\"Year less 1\", FORMAT([Date], \"yyyy\")-1,",
                "\"MonthYear\", FORMAT([Date],\"mmm yy\"),",
                "\"QuarterYear\", FORMAT([Date],\"yyyy \\QQ\"), ",
                "\"MonthNo\", MONTH([Date]),",
                "\"MonthText\", FORMAT([Date], \"mmm\"),",
                "\"YearMonth\", FORMAT([Date], \"MMMM-YYYY\"),",
                "\"YMInt\", 13 * YEAR([Date]) + MONTH([Date]),",
                "\"WeekdayNo\", WEEKDAY([Date],2),",
                "\"Year & Month\", FORMAT([Date],\"MMM-YY\"),",
                "\"Month\", FORMAT([Date], \"mmmm\"), ",
                "\"WeekNo\", WEEKNUM([Date]),",
                "\"EOW - Saturday\", [Date]+7-WEEKDAY([Date]-7),",
                "\"Weekday\", FORMAT([Date], \"dddd\"), ",
                "\"DayNo\", FORMAT([Date], \"d\"),",
                "\"DayMonth\", FORMAT([Date], \"dd mmm\")",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a3a1a0dd-88a5-4984-a4e2-03ea5e260406",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bc6917b3-b719-448f-8066-46ea8f56c57f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "85dee4b7-3c18-4a52-a22b-36cc0d7f4be3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b4400044-28c8-4bec-9e31-ea24bc3e852e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "7c5eeb8c-3477-4ee6-8b3f-9579a278c21a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e2d4bf57-e4a0-49b4-a089-ae7bdac649bd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a3217527-c230-4589-b12f-c6cde1495963",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ad1ac195-5b41-40f1-ac77-e69afa87e0e7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9c853174-9a34-41d1-a0d0-127a6714cfae",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8419fa58-c290-4dc1-a689-604454e32d71",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "79554b15-caf5-4b6a-8976-830d462e7b0a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2a5f1daf-45f2-4409-b294-d36b4df03c93",
                "ordinal": 3
              }
            ],
            "lineageTag": "02240728-9000-4d48-b46c-1372fa962a88"
          }
        ],
        "isHidden": true,
        "lineageTag": "9c532cd0-03a8-4854-a6c7-1a9b94ba4de2",
        "partitions": [
          {
            "name": "LocalDateTable_a3a1a0dd-88a5-4984-a4e2-03ea5e260406",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[Date])), 1, 1), Date(Year(MAX('Calendar'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_a1804b1c-1bd9-49ab-a9d3-60896ebf5886",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b3119d90-e628-4a77-a010-1226b27c1bfa",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "39740154-8848-4313-a9a1-a1ac93b77c3e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c02b0191-f646-43bc-b809-a20d3b342e0e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "21cfafa1-c565-476b-a8bd-bbcf7912307f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a765e72a-bfdc-41ad-bd4b-6eea5074e92a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "04ca3d44-a1fe-4589-a3bd-7ee0e60f0c8f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6a904ee6-c3e0-4452-9ed4-ee9444d2d571",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "60a96448-1dc8-4072-8b4d-319d33e99200",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b97da664-4185-4d9e-aaa7-1aaceacae5ad",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b2c06452-43e4-4853-8dd7-a2e92a28489b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "455c11bc-3a5c-4864-9db9-184a97ed1298",
                "ordinal": 3
              }
            ],
            "lineageTag": "57076584-58ff-46d5-90f2-2f495c037acc"
          }
        ],
        "isHidden": true,
        "lineageTag": "88283376-7b9d-4b0f-89ec-4d6446e893c8",
        "partitions": [
          {
            "name": "LocalDateTable_a1804b1c-1bd9-49ab-a9d3-60896ebf5886",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[EOW - Saturday])), 1, 1), Date(Year(MAX('Calendar'[EOW - Saturday])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}